octomap_server:
  ros__parameters:
    frame_id: "map"
    resolution: 0.1
    sensor_model/max_range: 30.0
    sensor_model/hit: 0.7
    sensor_model/miss: 0.4
    sensor_model/min: 0.12
    sensor_model/max: 0.97
    publish_free_space: true
    latch: false
